FROM adoptopenjdk:11-jdk-openj9

COPY oes-server-exam-basic-1.0.jar /oes-cloud/oes-server-exam-basic-1.0.jar
ENTRYPOINT [ \
    "java", \
    "-jar", \
    "/oes-cloud/oes-server-exam-basic-1.0.jar"\
]
